import { HackathonCard } from "@/components/hackathon-card";
import BlurFade from "@/components/magicui/blur-fade";
import BlurFadeText from "@/components/magicui/blur-fade-text";
import { ProjectCard } from "@/components/project-card";
import { ResumeCard } from "@/components/resume-card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { getBlogPosts } from "@/data/blog";
import { DATA } from "@/data/resume";
import { cn } from "@/lib/utils";
import { ChevronRightIcon } from "lucide-react";
import Link from "next/link";
import Markdown from "react-markdown";

import { getLastCommit } from 'last-commit-log';

import { Josefin_Sans } from "next/font/google";


const josefin_sans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400",
  display: "swap",
});

const BLUR_FADE_DELAY = 0.05;

export default async function Page() {
  let reacent_blog=await getBlogPosts();

  // const LCL = require('last-commit-log');
  // const lcl = new LCL();

  // const revision = await lcl.getLastCommit();

  reacent_blog=reacent_blog.sort((a, b) => {
    if (
      new Date(a.metadata.publishedAt) > new Date(b.metadata.publishedAt)
    ) {
      return -1;
    }
    return 1;
  });
  if (reacent_blog.length>3){
    reacent_blog=reacent_blog.slice(0,3);
  }

  return (
    <main className="flex flex-col min-h-[100dvh] space-y-10 print:space-y-5 print:min-h-fit">
      <section id="hero">
        <div className="mx-auto w-full max-w-2xl space-y-8">
          <div className="gap-2 flex justify-between">
            <div className="flex-col flex flex-1 space-y-1.5">
              <BlurFadeText
                delay={BLUR_FADE_DELAY}
                className={cn("text-3xl font-bold tracking-tighter sm:text-3xl xl:text-3xl/none print:hidden", josefin_sans.className)}
                yOffset={8}
                text={`Hi, I'm ${DATA.name.split(" ")[0]} 👋`}
              />
              <BlurFadeText
                delay={BLUR_FADE_DELAY * 2}
                className="text-2xl font-bold tracking-tighter sm:text-2xl xl:text-2xl/none hidden print:block"
                yOffset={8}
                text={'Zhang Huakang'}/>
              <BlurFade delay={BLUR_FADE_DELAY}>
                <Markdown className={cn("max-w-[600px] text-sm sm:text-base text-pretty print:hidden")}>
                  {DATA.description}
                </Markdown>
                <div className="flex items-center space-x-1 py-1 ml-[-10px]">
                  {
                    Object.entries(DATA.contact.social)
                      .filter(([_, social]) => social.navbar)
                      .map(([name,socail])=>(
                        <Tooltip
                        key={socail.url}
                        >
                        <TooltipTrigger asChild>
                        <Link
                          href={socail.url}
                          className={cn(
                            buttonVariants({ variant: "ghost", size: "icon" }),
                          )}
                          key={socail.url}
                          >
                            <socail.icon className="size-4"/>
                        </Link>
                        </TooltipTrigger>
                        <TooltipContent side="bottom">
                          <p>{socail.name}</p>
                        </TooltipContent>
                        </Tooltip>
                      ))
                  }
                </div>
              </BlurFade>
            </div>
            <BlurFade delay={BLUR_FADE_DELAY} className="print:hidden">
              <Tooltip delayDuration={1000}>
              <TooltipTrigger asChild>
              <Avatar className="size-32">
                <AvatarImage alt={DATA.name} src={DATA.avatarUrl} />
                <AvatarFallback>{DATA.initials}</AvatarFallback>
              </Avatar>
              </TooltipTrigger>
              <TooltipContent side="bottom" className="">
                <p>Generated by ChatGPT</p>
              </TooltipContent>
              </Tooltip>
            </BlurFade>
          </div>
        </div>
      </section>
      <section id="about" className="print:hidden">
        <BlurFade delay={BLUR_FADE_DELAY * 3}>
          <h2 className="font-bold text-lg pb-2">About</h2>
        </BlurFade>
        <BlurFade delay={BLUR_FADE_DELAY * 4}>
          <Markdown className="prose max-w-full text-pretty font-sans dark:prose-invert text-sm sm:text-base text-primary">
            {DATA.summary}
          </Markdown>
        </BlurFade>
      </section>

      <section id="education">
        <div className="flex min-h-0 flex-col gap-y-3">
          <BlurFade delay={BLUR_FADE_DELAY * 7}>
            <h2 className="text-xl font-bold">Education</h2>
          </BlurFade>
          {DATA.education.map((education, id) => (
            <BlurFade
              key={education.school}
              delay={BLUR_FADE_DELAY * 8 + id * 0.05}
            >
              <ResumeCard
                key={education.school}
                href={education.href}
                logoUrl={education.logoUrl}
                altText={education.school}
                title={education.school}
                subtitle={education.degree}
                period={`${education.start} - ${education.end}`}
              />
            </BlurFade>
          ))}
        </div>
      </section>
      
      <section id="experience">
        <div className="flex min-h-0 flex-col gap-y-3">
          <BlurFade delay={BLUR_FADE_DELAY * 5}>
            <h2 className="text-xl font-bold">Research Experience</h2>
          </BlurFade>
          {DATA.research_experience.map((work, id) => (
            <BlurFade
              key={work.company}
              delay={BLUR_FADE_DELAY * 6 + id * 0.05}
            >
              <ResumeCard
                key={work.company}
                logoUrl={work.logoUrl}
                altText={work.company}
                title={work.company}
                subtitle={work.title}
                href={work.href}
                badges={work.badges}
                period={`${work.start} - ${work.end ?? "Present"}`}
                description={work.description}
                location={work.location}
                lab={work.lab}
              />
            </BlurFade>
          ))}
        </div>
      </section>
      <section id="work">
        <div className="flex min-h-0 flex-col gap-y-3">
          <BlurFade delay={BLUR_FADE_DELAY * 5}>
            <h2 className="text-xl font-bold">Work Experience</h2>
          </BlurFade>
          {DATA.work.map((work, id) => (
            <BlurFade
              key={work.company}
              delay={BLUR_FADE_DELAY * 6 + id * 0.05}
            >
              <ResumeCard
                key={work.company}
                logoUrl={work.logoUrl}
                altText={work.company}
                title={work.company}
                subtitle={work.title}
                href={work.href}
                badges={work.badges}
                period={`${work.start} - ${work.end ?? "Present"}`}
                description={work.description}
                location={work.location}
              />
            </BlurFade>
          ))}
        </div>
      </section>

      <section id="projects" className="print:hidden">
        <div className="space-y-12 w-full">
          <BlurFade delay={BLUR_FADE_DELAY * 11}>
            <div className="space-y-2">
              <div className="text-xl font-bold">
                Projects
              </div>
            </div>
          </BlurFade>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 max-w-[800px] mx-auto">
            {DATA.projects.map((project, id) => (
              <BlurFade
                key={project.title}
                delay={BLUR_FADE_DELAY * 12 + id * 0.05}
              >
                <ProjectCard
                  href={project.href}
                  key={project.title}
                  title={project.title}
                  description={project.description}
                  dates={project.dates}
                  tags={project.technologies}
                  image={project.image}
                  video={project.video}
                  links={project.links}
                />
              </BlurFade>
            ))}
          </div>
        </div>
      </section>
      
    </main>
  );
}
